name: assign-peaks-to-cells
channels:
  - conda-forge
dependencies:
  - opencv == 4.1.2
  - scikit-image
  - dask
  - pandas
  - shapely
  - imagecodecs
  - pip:
    - fire
    - scanpy
    - leidenalg
